# Generated by Django 6.0.5 on 2026-05-20 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_description_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
